In [90]:
(50-5*6)/4

5.0

In [4]:
8/5

1.6

In [6]:
8//5

1

In [8]:
7//-3

-3

In [10]:
8//-5

-2

In [12]:
7/-3

-2.3333333333333335

In [14]:
7//3

2

In [16]:
_

2

In [20]:
list(range(5,9))

[5, 6, 7, 8]

In [43]:
a = [66.25, 333, 333, 1, 1234.5]

In [25]:
print(a.count(333), a.count(66.25))

2 1


In [27]:
a.insert(2, -1)

In [29]:
a

[66.25, 333, -1, -1, 333, 1, 1234.5]

In [32]:
a.index(66.25)

0

In [3]:
t = [12345, 54321, 'hello!']

In [4]:
t

[12345, 54321, 'hello!']

In [8]:
4*0.5

2.0

In [1]:
price, unit = 100.50, 50

In [22]:
print(f"Total :{unit*price:,.2f}")

Total :5,025.00


In [24]:
x=complex(2,-2)

In [31]:
x

(2-2j)

In [91]:
first_n,last_n = ' k a pil ','rathor'

In [39]:
print(first_n+' '+last_n)
print(len(first_n))

kapil rathor
5


In [48]:
'm' not in first_n

True

In [50]:
first_n*2

'kapilkapil'

In [93]:
first_n.strip()

'k a pil'

In [312]:
stu = [9,10,300,20,20]

In [17]:
stu.remove(20)

In [62]:
stu1 = stu.copy()

In [313]:
stu.sort()

In [66]:
stu.sort(reverse = True)

In [4]:
stu

[9, 10, 300, 20, 20]

In [85]:
stud = 1,3,7,55,88,88,34,34,'hi'

In [86]:
tuple(stud)

(1, 3, 7, 55, 88, 88, 34, 34, 'hi')

In [23]:
studs = {2,22,222,222,1,11,111,111}

In [13]:
studs.add(3)

In [25]:
studs.update([33,333])

In [28]:
studs1 = studs.copy()

In [26]:
studs

{1, 2, 11, 22, 33, 111, 222, 333}

In [29]:
studs1

{1, 2, 11, 22, 33, 111, 222, 333}

In [7]:
people = {'htanaka': 'Haru Tanaka','htanaka': 'Haru','ppatel': 'Priya Patel','bagarcia': 'Benjamin Alberto Garcia','zmin': 'Zhang Min','afarooqi': 'Ayesha Farooqi','hajackson': 'Hanna Jackson','papatel': 'Pratyush Aarav Patel','hrjackson': 'Henry Jackson'}

In [20]:
len(people)

8

In [8]:
people

{'htanaka': 'Haru',
 'ppatel': 'Priya Patel',
 'bagarcia': 'Benjamin Alberto Garcia',
 'zmin': 'Zhang Min',
 'afarooqi': 'Ayesha Farooqi',
 'hajackson': 'Hanna Jackson',
 'papatel': 'Pratyush Aarav Patel',
 'hrjackson': 'Henry Jackson'}

In [35]:
people.get('zmin','ppatel')

'Zhang Min'

In [37]:
people['htanaka'] = 'Haru T'

In [60]:
people.update({'kapilr': 'Kapil Rathore'})

In [45]:
people

{'htanaka': 'Haru T',
 'ppatel': 'Priya Patel',
 'bagarcia': 'Benjamin Alberto Garcia',
 'zmin': 'Zhang Min',
 'afarooqi': 'Ayesha Farooqi',
 'hajackson': 'Hanna Jackson',
 'papatel': 'Pratyush Aarav Patel',
 'hrjackson': 'Henry Jackson',
 'kapilr': 'Kapil Rathore'}

In [48]:
for person in people.keys():    print(person + " = " + people[person])

htanaka = Haru T
ppatel = Priya Patel
bagarcia = Benjamin Alberto Garcia
zmin = Zhang Min
afarooqi = Ayesha Farooqi
hajackson = Hanna Jackson
papatel = Pratyush Aarav Patel
hrjackson = Henry Jackson
kapilr = Kapil Rathore


In [50]:
people.keys()

dict_keys(['htanaka', 'ppatel', 'bagarcia', 'zmin', 'afarooqi', 'hajackson', 'papatel', 'hrjackson', 'kapilr'])

In [52]:
people.items()

dict_items([('htanaka', 'Haru T'), ('ppatel', 'Priya Patel'), ('bagarcia', 'Benjamin Alberto Garcia'), ('zmin', 'Zhang Min'), ('afarooqi', 'Ayesha Farooqi'), ('hajackson', 'Hanna Jackson'), ('papatel', 'Pratyush Aarav Patel'), ('hrjackson', 'Henry Jackson'), ('kapilr', 'Kapil Rathore')])

In [54]:
people.values()

dict_values(['Haru T', 'Priya Patel', 'Benjamin Alberto Garcia', 'Zhang Min', 'Ayesha Farooqi', 'Hanna Jackson', 'Pratyush Aarav Patel', 'Henry Jackson', 'Kapil Rathore'])

In [57]:
people.clear()

In [62]:
people

{'htanaka': 'Haru',
 'ppatel': 'Priya Patel',
 'bagarcia': 'Benjamin Alberto Garcia',
 'zmin': 'Zhang Min',
 'afarooqi': 'Ayesha Farooqi',
 'hajackson': 'Hanna Jackson',
 'papatel': 'Pratyush Aarav Patel',
 'hrjackson': 'Henry Jackson',
 'kapilr': 'Kapil Rathore'}

In [77]:
poeple1 = people.fromkeys('kapilr','Kapil Rathore')

In [79]:
poeple1

{'k': 'Kapil Rathore',
 'a': 'Kapil Rathore',
 'p': 'Kapil Rathore',
 'i': 'Kapil Rathore',
 'l': 'Kapil Rathore',
 'r': 'Kapil Rathore'}

In [9]:
people.pop('kapilr')

KeyError: 'kapilr'

In [7]:
people.popitem()

('hrjackson', 'Henry Jackson')

In [10]:
people

{'htanaka': 'Haru',
 'ppatel': 'Priya Patel',
 'bagarcia': 'Benjamin Alberto Garcia',
 'zmin': 'Zhang Min',
 'afarooqi': 'Ayesha Farooqi',
 'hajackson': 'Hanna Jackson',
 'papatel': 'Pratyush Aarav Patel'}

In [16]:
people.setdefault('htanaka')

'Haru'

In [5]:
people

NameError: name 'people' is not defined

In [15]:
poeple1 = people.copy()

In [45]:
poeple1

{'ppatel': 'Priya Patel',
 'bagarcia': 'Benjamin Alberto Garcia',
 'zmin': 'Zhang Min',
 'afarooqi': 'Ayesha Farooqi',
 'hajackson': 'Hanna Jackson',
 'papatel': 'Pratyush Aarav Patel'}

In [46]:
del poeple1["ppatel"]

In [16]:
poeple1.clear()

In [17]:
poeple1

{}

In [18]:
people

{'htanaka': 'Haru',
 'ppatel': 'Priya Patel',
 'bagarcia': 'Benjamin Alberto Garcia',
 'zmin': 'Zhang Min',
 'afarooqi': 'Ayesha Farooqi',
 'hajackson': 'Hanna Jackson',
 'papatel': 'Pratyush Aarav Patel',
 'hrjackson': 'Henry Jackson'}

In [29]:
def hello(a = 'nobody'):    print('Hello'+ a)

In [32]:
def sorter(*args):    
    """ Pass in any number of arguments separated by commas    Inside the function, they treated as a tuple named args """    
    # The passed-in    # Create a list from the passed-in tuple   
    newlist = list(args)    # Sort and show the list.    
    newlist.sort()    
    print(newlist)

In [34]:
sorter(5,3,77,22,345,1)

[1, 3, 5, 22, 77, 345]


In [38]:
def alphabetize(original_list=[]):    
    """ Pass any list in square brackets, displays a string with items sorted """    
    # Inside the function make a working copy of the list passed in.    
    sorted_list = original_list.copy()    # Sort the working copy.    
    sorted_list.sort()    # Make a new empty string for output    
    final_list = ''    # Loop through sorted list and append name and comma and space.    
    for name in sorted_list:        
        final_list += name + ', '    # Knock of last comma space if final list is long enough    
    final_list = final_list[:-2]    # Print the alphabetized list.    
    print(final_list)

In [45]:
alphabetize(['me','wife','son','dad'])

dad, me, son, wife


In [1]:
sorter('me','wife','son','dad')

NameError: name 'sorter' is not defined

In [3]:
names = ['Adams', 'Ma', 'diMeola', 'Zandusky'] 
names.sort(key=lambda s: s.lower()) 
print(names)

['Adams', 'diMeola', 'Ma', 'Zandusky']


In [7]:
# Show number in currency format. 
def currency(n):    
    return f"${n:,.2f}"

In [9]:
currency(2)

'$2.00'

In [35]:
# Define a new class name Member. 
class Member:    
    """ Create a new member. """    
    def __init__(self, uname , fname = 'none'):        
        # Define attributes and give them values
        self.username = uname
        self.fullname = fname

In [38]:
new_guy = Member()

TypeError: __init__() missing 1 required positional argument: 'uname'

In [37]:
new_guy.username

'kapil'

In [24]:
new_guy.username = 'neha'

In [39]:
new_guy.username

'kapil'

In [52]:
# Define a new class name Member. 
class Member:    
    """ Create a new member. """    
    def __init__(self, uname , fname):        
        # Define attributes and give them values
        print(uname,fname)

In [53]:
new_guy = Member('kapil','rathor')

kapil rathor


In [20]:
class Member:    
    """ The Member class attributes and methods """   
    # Initialize a member object.    
    def __init__(self, firstname, lastname):        
        # Attributes (instance variables) for everybody.        
        self.firstname = firstname        
        self.lastname = lastname 
    # Method in the base class    
    def get_status(self):        
        return  f"{self.firstname} is a Member." 
# Subclass for Administrators class Admin(Member):    
def get_status(self):        
    return  f"{self.firstname} is an Admin." 
# Subclass for regular Users class User(Member):    
def get_status(self):        
    return  f"{self.firstname} is a regular User."

In [5]:
print('Do this first') 
try:    
    open('people.csv') 
except FileNotFoundError:    
    print('Cannot find file named people.csv') 
except Exception as e:    
    print('e') 
else:    
    print('Show this if no exception.') 
finally:    
    print('This is in the finally block') 
print("This is outside the try...except...else...finally")

Do this first
Cannot find file named people.csv
This is in the finally block
This is outside the try...except...else...finally


In [130]:
with open('mobile_cleaned.txt') as f: # Read in entire file    
    content = f.readline()    
    print(content)

In [34]:
'doesn\'t'

"doesn't"

In [172]:
a[:0]=a

In [173]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [61]:
q = [2, 3]
p = [1, q, 4]

In [63]:
p

[1, [2, 3], 4]

In [70]:
matrix = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]] 

In [50]:
matset = {{1, 2, 3, 4},{5, 6, 7, 8},{9, 10, 11, 12}}

TypeError: unhashable type: 'set'

In [48]:
mat

NameError: name 'mat' is not defined

In [103]:
for x in range(1, 11): 
    print("{:2d}{:3d}{:4d}".format(x, x*x, x*x*x))

 1  1   1
 2  4   8
 3  9  27
 4 16  64
 5 25 125
 6 36 216
 7 49 343
 8 64 512
 9 81 729
101001000


In [108]:
'-3.14'.zfill(7)

'-003.14'

In [115]:
print('Wearethe{}whosay "{}!"'.format('knights', 'Ni'))
print('{0} and {1}'.format('spam', 'eggs'))
print('{1} and {0}'.format('spam', 'eggs'))
print('This {food} is {adjective}.'.format(food='spam', adjective='absolutely horrible'))
print('Thestoryof {0}, {1},and {other}.'.format('Bill', 'Manfred', other='Georg'))
      

Wearetheknightswhosay "Ni!"
spam and eggs
eggs and spam
This spam is absolutely horrible.
Thestoryof Bill, Manfred,and Georg.


In [118]:
import math 
print('The value of PI is approximately %5.3f.' % math.pi)

The value of PI is approximately 3.142.


In [149]:
with open('mobile_cleaned.txt','w') as f: # Read in entire file   
    f.write('Kapil Rathor')
    f.close()

In [150]:
with open('mobile_cleaned.txt','r') as f: # Read in entire file    
    content = f.readline()  
    print(content)
    f.close()

Kapil Rathor


In [1]:
import pickle
x = 'Shivalee Rathor'
with open('mobile_cleaned.txt') as f: # Read in entire file    
    pickle.dump(x,f)

TypeError: write() argument must be str, not bytes

In [3]:
matrix = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]] 

In [46]:
[[row[i] for row in matrix] for i in range(len(matrix[0]))]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [42]:
for i in matrix:
    for j in i:
        print(j,end=' ')


1 2 3 4 5 6 7 8 9 10 11 12 

In [43]:
[num for elem in matrix for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [52]:
mat = ((1, 2, 3, 4),(5, 6, 7, 8),(9, 10, 11, 12))

In [54]:
[[row[i] for row in mat] for i in range(len(mat[0]))]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [56]:
matdict = {{'a':1, 'b':2, 'c':3, 'd':4},{'e':5, 'f':6, 'g':7, 'h':8},{'i':9, 'j':10, 'k':11, 'l':12}}

TypeError: unhashable type: 'dict'

In [3]:
import numpy as np

In [283]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]], float)

In [149]:
a[2,0]

7.0

In [161]:
a[-1:,:]

array([[7., 8., 9.]])

In [162]:
a[-1]

array([7., 8., 9.])

In [157]:
a[-1:]

array([[7., 8., 9.]])

In [230]:
b = a[:0,:0]

In [231]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [224]:
c = [[1, 2, 3], [4, 5, 6],[7, 8, 9]]

In [226]:
c = np.array(range(10), float)

In [236]:
c = c.reshape((5,2))

In [238]:
c

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [263]:
l = [1, 2, 3]

In [264]:
l1 = l

In [265]:
l2 = l.copy()

In [269]:
l[0] = 0

In [270]:
l

[0, 2, 3]

In [271]:
l1

[0, 2, 3]

In [273]:
l2

[1, 2, 3]

In [286]:
a.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

In [279]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [284]:
list(a)

[array([1., 2., 3.]), array([4., 5., 6.]), array([7., 8., 9.])]

In [287]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [291]:
b = a.tostring()

In [293]:
b

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @\x00\x00\x00\x00\x00\x00"@'

In [295]:
np.fromstring(b)

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [298]:
a.fill(0)

In [300]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [302]:
a = np.array(range(6), float).reshape((2, 3))

In [304]:
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [307]:
a.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [314]:
a.flatten()

array([0., 1., 2., 3., 4., 5.])

In [321]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [328]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
np.concatenate((a,b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [330]:
np.concatenate((a,b), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [332]:
np.concatenate((a,b), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [335]:
a = np.array([1, 2, 3], float)

In [337]:
a

array([1., 2., 3.])

In [339]:
a[:,np.newaxis]

array([[1.],
       [2.],
       [3.]])

In [341]:
a

array([1., 2., 3.])

In [361]:
a = np.array([[1, 2], [3, 4]], float)

In [366]:
a.shape

(2, 2)

In [367]:
a[:,np.newaxis].shape

(2, 1, 2)

In [369]:
a[np.newaxis, :].shape

(1, 2, 2)

In [371]:
a

array([[1., 2.],
       [3., 4.]])

In [374]:
np.arange(5, dtype=float)

array([0., 1., 2., 3., 4.])

In [376]:
np.arange(1, 6, 2, dtype=int)

array([1, 3, 5])

In [379]:
np.ones((2,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [394]:
np.zeros((7,2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [383]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [385]:
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [387]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [389]:
np.identity(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [391]:
np.eye(4, k=1, dtype=float)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [395]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)
a * b

array([[ 2.,  0.],
       [ 3., 12.]])

In [397]:
a = np.zeros((2,2), float)
b = np.array([-1., 3.], float)

In [399]:
a

array([[0., 0.],
       [0., 0.]])

In [401]:
b

array([-1.,  3.])

In [403]:
a + b[np.newaxis,:]

array([[-1.,  3.],
       [-1.,  3.]])

In [405]:
a + b[:,np.newaxis]

array([[-1., -1.],
       [ 3.,  3.]])

In [406]:
np.sqrt(a)
np.floor(a)
np.ceil(a)
np.rint(a)
np.pi
np.e

2.718281828459045

In [412]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x,y in a:
    print (x,y)

1.0 2.0
3.0 4.0
5.0 6.0


In [414]:
a = np.array([2, 4, 3], float)
a.sum()
a.prod()
a.mean()
a.var()
a.std()
a.min()
a.max()
a.argmin()
a.argmax()

1

In [5]:
a = np.array([[0, 2], [3, -1], [3, 5]], float)
a.mean(axis=0)
a.mean(axis=1)
a.min(axis=1)
a.max(axis=0)

array([2., 2.])

In [422]:
a = np.array([6, 2, 5, -1, 0], float)
sorted(a)
a.sort()
a.clip(0, 5)

array([0., 0., 2., 5., 5.])

In [424]:
a

array([-1.,  0.,  2.,  5.,  6.])

In [426]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
np.unique(a)

array([1., 4., 5., 7.])

In [428]:
a = np.array([[1, 2], [3, 4]], float)
a.diagonal()

array([1., 4.])

In [431]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
c = a > b

In [434]:
any(c)
all(c)

False

In [438]:
a = np.array([1, 3, 0], float)
c = np.array([2, 3, 0], float)
np.logical_and(a > 0, a < 3)
np.logical_not(b)
np.logical_or(a, c)

array([ True,  True, False])

In [441]:
a = np.array([1, 3, 0], float)
np.where(a != 0, 1 / a, a)
np.where(a > 0, 3, 2)

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([3, 3, 2])

In [443]:
a = np.array([[0, 1], [3, 0]], float)
a.nonzero()

(array([0, 1], dtype=int64), array([1, 0], dtype=int64))

In [445]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [448]:
np.isnan(a)
np.isfinite(a)

array([ True, False, False])

In [452]:
a = np.array([[6, 4], [5, 9]], float)
a >= 6
a[a >= 6]
a[np.logical_and(a > 5, a < 9)]

array([6.])

In [456]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[[0, 0, 1, 3, 2, 1]]
a[b]
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [458]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [460]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([0, 0, 1], int)
a.take(b, axis=0)

array([[0., 1.],
       [0., 1.],
       [2., 3.]])

In [462]:
a.take(b, axis=1)

array([[0., 0., 1.],
       [2., 2., 3.]])

In [466]:
a = np.array([0, 1, 2, 3, 4, 5], float)
b = np.array([9, 8, 7], float)
a.put([0, 3], b)
a

array([9., 1., 2., 8., 4., 5.])

In [467]:
a

array([9., 1., 2., 8., 4., 5.])

In [469]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
a

array([[0., 1.],
       [2., 3.]])

In [472]:
np.dot(b, a)

array([ 6., 11.])

In [474]:
np.dot(a, b)

array([ 3., 13.])

In [476]:
np.dot(a, c)

array([[ 4.,  0.],
       [14.,  2.]])

In [478]:
np.dot(c, a)

array([[2., 4.],
       [0., 4.]])

In [480]:
a = np.array([1, 4, 0], float)
b = np.array([2, 2, 1], float)

In [482]:
np.outer(a, b)

array([[2., 2., 1.],
       [8., 8., 4.],
       [0., 0., 0.]])

In [484]:
np.inner(a, b)

10.0

In [486]:
np.cross(a, b)

array([ 4., -1., -6.])

In [488]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
a

array([[4., 2., 0.],
       [9., 3., 7.],
       [1., 2., 1.]])

In [490]:
np.linalg.det(a)

-48.00000000000003

In [492]:
vals, vecs = np.linalg.eig(a)
vals

array([ 8.85591316,  1.9391628 , -2.79507597])

In [494]:
vecs

array([[-0.3663565 , -0.54736745,  0.25928158],
       [-0.88949768,  0.5640176 , -0.88091903],
       [-0.27308752,  0.61828231,  0.39592263]])

In [497]:
b = np.linalg.inv(a)
b

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [499]:
np.dot(a, b)

array([[ 1.00000000e+00,  0.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [501]:
a = np.array([[1, 3, 4], [5, 2, 3]], float)
U, s, Vh = np.linalg.svd(a)
U

array([[-0.6113829 , -0.79133492],
       [-0.79133492,  0.6113829 ]])

In [503]:
s

array([7.46791327, 2.86884495])

In [505]:
Vh

array([[-0.61169129, -0.45753324, -0.64536587],
       [ 0.78971838, -0.40129005, -0.46401635],
       [-0.046676  , -0.79349205,  0.60678804]])

In [507]:
np.poly([-1, 1, 1, 10])

array([  1., -11.,   9.,  11., -10.])

In [509]:
np.roots([1, 4, -2, 3])

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

In [511]:
np.polyint([1, 1, 1, 1])

array([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

In [513]:
np.polyder([1./4., 1./3., 1./2., 1., 0.])

array([1., 1., 1., 1.])

In [515]:
np.polyval([1, -2, 0, 2], 4)

34

In [517]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0, 2, 1, 3, 7, 10, 11, 19]
np.polyfit(x, y, 2) 

array([ 0.375     , -0.88690476,  1.05357143])

In [519]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float)
np.median(a)

3.0

In [523]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
c = np.corrcoef(a)
c

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [525]:
np.cov(a)

array([[0.91666667, 2.08333333],
       [2.08333333, 8.91666667]])

In [27]:
np.random.seed(293423)

In [22]:
np.random.rand(5)

array([0.84612516, 0.0704939 , 0.1526965 , 0.77831701, 0.80821151])

In [29]:
np.random.rand(2,3)

array([[0.0704939 , 0.1526965 , 0.77831701],
       [0.80821151, 0.82198398, 0.90239653]])

In [31]:
np.random.random()

0.026385653984089985

In [33]:
np.random.randint(5, 10) 

5

In [35]:
np.random.poisson(6.0)

7

In [37]:
np.random.normal(1.5, 4.0)

-6.004397158275498

In [39]:
np.random.normal()

0.30850928808259

In [41]:
np.random.normal(size=5)

array([ 0.42575555, -0.16336711, -0.56744115, -1.00445192,  0.05687602])

In [49]:
l = range(10)
l

range(0, 10)

In [51]:
 np.random.shuffle(l)

TypeError: 'range' object does not support item assignment

In [53]:
import pandas as pd

In [67]:
a = pd.DataFrame({'A': 1.,'B': pd.Timestamp('20130102'),'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),'E': pd.Categorical(["test", "train", "test", "train"]),'F': 'foo'})

In [57]:
a

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [65]:
b = pd.DataFrame(np.random.randn(6, 4),index = dates, columns=list('ABCD'))

In [68]:
b

A         B         C         D
0  0.837408 -0.419924 -1.114266  0.693327
1  0.715375  1.507535  1.027117 -1.005253
2 -0.424304  0.098895 -0.292976 -0.466803
3 -0.480848  0.084883  1.198362  0.834684
4  1.006964 -1.569642 -0.394980  0.554173
5  0.381749 -0.875052 -0.410955  1.592338

In [75]:
a.head(2)
a.tail(1)

A          B    C  D      E    F
3  1.0 2013-01-02  1.0  3  train  foo

In [77]:
a.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [81]:
a.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [82]:
a.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [85]:
a.describe()

A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

In [87]:
a.T

0                    1                    2  \
A                    1                    1                    1   
B  2013-01-02 00:00:00  2013-01-02 00:00:00  2013-01-02 00:00:00   
C                    1                    1                    1   
D                    3                    3                    3   
E                 test                train                 test   
F                  foo                  foo                  foo   

                     3  
A                    1  
B  2013-01-02 00:00:00  
C                    1  
D                    3  
E                train  
F                  foo

In [90]:
b.sort_index(axis=1, ascending=False)

D         C         B         A
0  0.693327 -1.114266 -0.419924  0.837408
1 -1.005253  1.027117  1.507535  0.715375
2 -0.466803 -0.292976  0.098895 -0.424304
3  0.834684  1.198362  0.084883 -0.480848
4  0.554173 -0.394980 -1.569642  1.006964
5  1.592338 -0.410955 -0.875052  0.381749

In [92]:
b.sort_values(by='B')

A         B         C         D
4  1.006964 -1.569642 -0.394980  0.554173
5  0.381749 -0.875052 -0.410955  1.592338
0  0.837408 -0.419924 -1.114266  0.693327
3 -0.480848  0.084883  1.198362  0.834684
2 -0.424304  0.098895 -0.292976 -0.466803
1  0.715375  1.507535  1.027117 -1.005253

In [118]:
a.loc[0:3,'A']

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

In [115]:
a.at[2,'A']

1.0

a.iloc[0:3,0:1]

In [120]:
a.iloc[0:3,0:2]

A          B
0  1.0 2013-01-02
1  1.0 2013-01-02
2  1.0 2013-01-02

In [122]:
a.iloc[[0,2],[1,3]]

B  D
0 2013-01-02  3
2 2013-01-02  3

In [124]:
a.iat[1,1]

Timestamp('2013-01-02 00:00:00')

In [126]:
b[b > 0]

A         B         C         D
0  0.837408       NaN       NaN  0.693327
1  0.715375  1.507535  1.027117       NaN
2       NaN  0.098895       NaN       NaN
3       NaN  0.084883  1.198362  0.834684
4  1.006964       NaN       NaN  0.554173
5  0.381749       NaN       NaN  1.592338

In [138]:
c = b.copy()

In [143]:
c['G'] = [11,22,33,44,55,66]

In [146]:
c

A         B         C         D   E   G
0  0.837408 -0.419924 -1.114266  0.693327  11  11
1  0.715375  1.507535  1.027117 -1.005253  22  22
2 -0.424304  0.098895 -0.292976 -0.466803  33  33
3 -0.480848  0.084883  1.198362  0.834684  44  44
4  1.006964 -1.569642 -0.394980  0.554173  55  55
5  0.381749 -0.875052 -0.410955  1.592338  66  66

In [148]:
c[c['E'].isin([33,55])]

A         B         C         D   E   G
2 -0.424304  0.098895 -0.292976 -0.466803  33  33
4  1.006964 -1.569642 -0.394980  0.554173  55  55

In [151]:
 s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range('20130102',periods=6))

In [153]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [164]:
b = b.reindex(index=[0:2], columns=list(b.columns) + ['E'])

SyntaxError: invalid syntax (<ipython-input-164-510a30656dfe>, line 1)

In [159]:
c.loc[0:2, 'E'] = 1

In [165]:
c.columns

Index(['A', 'B', 'C', 'D', 'E', 'G'], dtype='object')

In [178]:
d = b[b > -1]

In [179]:
d

A         B         C         D
0  0.837408 -0.419924       NaN  0.693327
1  0.715375  1.507535  1.027117       NaN
2 -0.424304  0.098895 -0.292976 -0.466803
3 -0.480848  0.084883  1.198362  0.834684
4  1.006964       NaN -0.394980  0.554173
5  0.381749 -0.875052 -0.410955  1.592338

In [182]:
d.dropna()
d.dropna(how = 'any')

A         B         C         D
2 -0.424304  0.098895 -0.292976 -0.466803
3 -0.480848  0.084883  1.198362  0.834684
5  0.381749 -0.875052 -0.410955  1.592338

In [185]:
d.fillna(value = 5)

A         B         C         D
0  0.837408 -0.419924  5.000000  0.693327
1  0.715375  1.507535  1.027117  5.000000
2 -0.424304  0.098895 -0.292976 -0.466803
3 -0.480848  0.084883  1.198362  0.834684
4  1.006964  5.000000 -0.394980  0.554173
5  0.381749 -0.875052 -0.410955  1.592338

In [187]:
pd.isna(d)

A      B      C      D
0  False  False   True  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False   True  False  False
5  False  False  False  False

In [190]:
d.mean()

A    0.339391
B    0.079268
C    0.225314
D    0.641544
dtype: float64

In [192]:
d.mean(1)

0    0.370271
1    1.083343
2   -0.271297
3    0.409270
4    0.388719
5    0.172020
dtype: float64

In [194]:
s = pd.Series([1, 3, 5, np.nan, 6, 8]).shift(2)

In [196]:
s

0    NaN
1    NaN
2    1.0
3    3.0
4    5.0
5    NaN
dtype: float64

In [200]:
b.sub(s, axis='index')

A         B         C         D
0       NaN       NaN       NaN       NaN
1       NaN       NaN       NaN       NaN
2 -1.424304 -0.901105 -1.292976 -1.466803
3 -3.480848 -2.915117 -1.801638 -2.165316
4 -3.993036 -6.569642 -5.394980 -4.445827
5       NaN       NaN       NaN       NaN

In [203]:
b.apply(np.cumsum)

A         B         C         D
0  0.837408 -0.419924 -1.114266  0.693327
1  1.552784  1.087611 -0.087148 -0.311926
2  1.128480  1.186507 -0.380124 -0.778729
3  0.647632  1.271390  0.818238  0.055954
4  1.654597 -0.298252  0.423258  0.610128
5  2.036345 -1.173304  0.012303  2.202465

In [205]:
b.apply(lambda x: x.max() - x.min())

A    1.487812
B    3.077177
C    2.312628
D    2.597591
dtype: float64

In [209]:
s = pd.Series(np.random.randint(0, 7, size=10))

In [212]:
s.value_counts()

1    3
4    2
2    2
6    1
5    1
0    1
dtype: int64

In [214]:
b.apply(np.mean)

A    0.339391
B   -0.195551
C    0.002051
D    0.367078
dtype: float64

In [216]:
b.apply(np.mean, axis = 1)

0   -0.000863
1    0.561194
2   -0.271297
3    0.409270
4   -0.100871
5    0.172020
dtype: float64

In [223]:
a.agg(['sum', 'mean'])

A    C     D             F
sum   4.0  4.0  12.0  foofoofoofoo
mean  1.0  1.0   3.0           NaN

In [225]:
a['A'].agg(['sum', lambda x: x.mean()])

sum         4.0
<lambda>    1.0
Name: A, dtype: float64

In [228]:
b.agg({'A': ['mean', 'min'], 'B': 'sum'})

A         B
mean  0.339391       NaN
min  -0.480848       NaN
sum        NaN -1.173304

In [230]:
b.transform([np.abs, lambda x: x + 1])

A                   B                   C                   D  \
   absolute  <lambda>  absolute  <lambda>  absolute  <lambda>  absolute   
0  0.837408  1.837408  0.419924  0.580076  1.114266 -0.114266  0.693327   
1  0.715375  1.715375  1.507535  2.507535  1.027117  2.027117  1.005253   
2  0.424304  0.575696  0.098895  1.098895  0.292976  0.707024  0.466803   
3  0.480848  0.519152  0.084883  1.084883  1.198362  2.198362  0.834684   
4  1.006964  2.006964  1.569642 -0.569642  0.394980  0.605020  0.554173   
5  0.381749  1.381749  0.875052  0.124948  0.410955  0.589045  1.592338   

             
   <lambda>  
0  1.693327  
1 -0.005253  
2  0.533197  
3  1.834684  
4  1.554173  
5  2.592338

In [232]:
arr = np.random.randn(20)

In [234]:
pd.cut(arr, 4)

[(-0.574, 0.326], (-0.574, 0.326], (1.226, 2.126], (1.226, 2.126], (1.226, 2.126], ..., (0.326, 1.226], (-0.574, 0.326], (-1.478, -0.574], (0.326, 1.226], (-1.478, -0.574]]
Length: 20
Categories (4, interval[float64]): [(-1.478, -0.574] < (-0.574, 0.326] < (0.326, 1.226] < (1.226, 2.126]]

In [236]:
b.transform({'A': np.abs, 'B': [lambda x: x + 1, 'sqrt']})

A         B          
   absolute  <lambda>      sqrt
0  0.837408  0.580076       NaN
1  0.715375  2.507535  1.227817
2  0.424304  1.098895  0.314476
3  0.480848  1.084883  0.291348
4  1.006964 -0.569642       NaN
5  0.381749  0.124948       NaN

In [244]:
d = ['FB', '2001-08-02', 90, 3.2]

In [253]:
ds = pd.Series(d, index = ['name', 'date', 'shares', 'price'])

In [256]:
ds['name']

'FB'

In [275]:
data = {'name' : ['AA', 'IBM', 'GOOG'],'date' : ['2001-12-01', '2012-02-10', '2010-04-09'],'shares' : [100, 30, 90],'price' : [12.3, 10.3, 32.2] }

In [289]:
a = pd.DataFrame(data)

In [264]:
a.index = ['one', 'two', 'three']

In [272]:
a

date  shares  price
name                           
AA    2001-12-01     100   12.3
IBM   2012-02-10      30   10.3
GOOG  2010-04-09      90   32.2

In [278]:
a = a.set_index(['date'])

In [291]:
a

name        date  shares  price
0    AA  2001-12-01     100   12.3
1   IBM  2012-02-10      30   10.3
2  GOOG  2010-04-09      90   32.2

In [294]:
a.drop('shares',axis = 1)

name        date  price
0    AA  2001-12-01   12.3
1   IBM  2012-02-10   10.3
2  GOOG  2010-04-09   32.2

In [298]:
a.sort_index()

name        date  shares  price
0    AA  2001-12-01     100   12.3
1   IBM  2012-02-10      30   10.3
2  GOOG  2010-04-09      90   32.2

In [299]:
a.sort_values('price')

name        date  shares  price
1   IBM  2012-02-10      30   10.3
0    AA  2001-12-01     100   12.3
2  GOOG  2010-04-09      90   32.2