In [ ]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
x = torch.rand(3,2)

In [ ]:
torch.empty(3,2)

tensor([[8.9260e-36, 0.0000e+00],
        [1.5975e-43, 1.3873e-43],
        [1.4574e-43, 6.4460e-44]])

In [ ]:
x = torch.empty(3,2)
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
y.size()

torch.Size([3, 2])

In [ ]:
x[:,1]

tensor([0.4348, 0.7670, 0.8175])

In [ ]:
x

tensor([[0.5450, 0.4348],
        [0.5139, 0.7670],
        [0.6081, 0.8175]])

In [ ]:
x[1,1].item()

0.7669589519500732

In [ ]:
y=x.view(2,3)

In [ ]:
y

tensor([[0.5450, 0.4348, 0.5139],
        [0.7670, 0.6081, 0.8175]])

In [ ]:
y.view(6,-1)

tensor([[0.5450],
        [0.4348],
        [0.5139],
        [0.7670],
        [0.6081],
        [0.8175]])

In [ ]:
y.view(-1,1)

tensor([[0.5450],
        [0.4348],
        [0.5139],
        [0.7670],
        [0.6081],
        [0.8175]])

In [ ]:
x = torch.ones([3, 2])
y = torch.ones([3, 2])
z = x + y
print(z)
z = x - y
print(z)
z = x * y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
x_np = x.numpy()
print(type(x), type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
a = np.random.randn(5)
print(a)
a_pt = torch.from_numpy(a)
print(type(a), type(a_pt))
print(a_pt)

[ 0.25125749  1.65314922 -0.59009345 -0.23916679 -0.11675177]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([ 0.2513,  1.6531, -0.5901, -0.2392, -0.1168], dtype=torch.float64)


In [ ]:
torch.add(x,y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [ ]:
x= torch.randn(2,2)
y= torch.randn(2,2)
torch.matmul(x,y)

tensor([[-1.3091, -1.6493],
        [ 1.1207,  1.2775]])

In [ ]:
x = torch.ones([3,2],requires_grad= True)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)

In [ ]:
y = x + 5
z= torch.sum(y)

In [ ]:
z.backward()

In [ ]:
print(z.grad)

None


/usr/local/lib/python3.6/dist-packages/torch/tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


In [ ]:
x = torch.ones([3, 2], requires_grad=True)
y = x + 5
r = 1/(1 + torch.exp(-y))
print(r)
s = torch.sum(r)
s.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [ ]:
x = torch.ones([3, 2], requires_grad=True)
y = x + 5
r = 1/(1 + torch.exp(-y))
a = torch.ones([3, 2])
r.backward(a)
print(x.grad)

tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [ ]:
learning_rate = 0.01

w = torch.tensor([1.0],requires_grad = True)
b = torch.tensor([1.0],requires_grad = True)

print(w.item(),b.item())

for i in range(10):
  x = torch.randn([20,1])
  y = 3*x - 2

  y_hat = w*x + b
  loss = torch.sum((y_hat - y)**2)
  loss.backward()
  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad

    w.grad.zero_()
    b.grad.zero_()

  print(w.item(),b.item())


1.0 1.0
1.5238656997680664 0.08685141801834106
1.9234623908996582 -0.45987194776535034
2.3183343410491943 -1.136755347251892
2.5497400760650635 -1.3661155700683594
2.770020008087158 -1.6322985887527466
2.9430112838745117 -1.7801717519760132
2.970102071762085 -1.8710205554962158
2.9887330532073975 -1.9244529008865356
2.992105484008789 -1.9545421600341797
2.9908528327941895 -1.971779465675354


In [ ]:
torch.cuda.device_count()

0

In [ ]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

RuntimeError: ignored