In [57]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

# Commonly used modules
import numpy as np
import os
import sys

# Images, plots, display, and visualization
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import cv2
import IPython
from six.moves import urllib

print(tf.__version__)

2.2.0


In [0]:
m1 = tf.constant([[2,2]])
m2 = tf.constant([[3],[3]])
dot_operation = tf.matmul(m1,m2)
print(dot_operation)

tf.Tensor([[12]], shape=(1, 1), dtype=int32)


In [0]:
var = tf.Variable(8)
add_operation = tf.add(var, 1)          # returns var + 1 of same type as var

In [0]:
print(add_operation)

tf.Tensor(9, shape=(), dtype=int32)


In [0]:
# Build a graph.
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b

# Launch the graph in a session.
sess = tf.compat.v1.Session()

# Evaluate the tensor `c`.
print(sess.run(c))

RuntimeError: ignored

In [0]:
# Build a dataflow graph.
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
e = tf.matmul(c, d)

print(e)

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)


In [0]:
#Lazy evaluation with session V1

tf.compat.v1.disable_eager_execution()

print(tf.__version__)

# Build a dataflow graph.
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
e = tf.matmul(c, d)

# Construct a `Session` to execute the graph.
sess = tf.compat.v1.Session()

# Execute the graph and store the value that `e` represents in `result`.
result = sess.run(e)
print(result)

2.2.0
[[1. 3.]
 [3. 7.]]


In [0]:
m1 = tf.constant([[2,2]])
m2 = tf.constant([[3],[3]])
dot_operation = tf.matmul(m1,m2)
print(dot_operation)

Tensor("MatMul_1:0", shape=(1, 1), dtype=int32)


In [0]:
sess = tf.compat.v1.Session()
result = sess.run(dot_operation)
print(result)
sess.close()

[[12]]


In [0]:
# Alternate way to run
with tf.compat.v1.Session() as sess:
    result_ = sess.run(dot_operation)
    print(result_)

[[12]]


In [0]:
var = tf.Variable(12)
add_operation = tf.add(var, 12)          # returns var + 1 of same type as var
update_operation = tf.compat.v1.assign(var, add_operation)      # var will hold new value add_operation

In [32]:
with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    for _ in range(3):
        sess.run(update_operation)
        print(sess.run(var))

24
36
48


In [0]:
x1 = tf.compat.v1.placeholder(dtype=tf.float32, shape=None)
y1 = tf.compat.v1.placeholder(dtype=tf.float32, shape=None)
z1 = x1 + y1

x2 = tf.compat.v1.placeholder(dtype=tf.float32, shape=[2,1])
y2 = tf.compat.v1.placeholder(dtype=tf.float32, shape=[1,2])
z2 = tf.matmul(x2, y2)

In [35]:
with tf.compat.v1.Session() as sess:
    # running one operation
    z1_value = sess.run(z1, feed_dict={x1: 5, y1: 6})
    print(z1_value)
    
    # running two operations at once
    z1_value, z2_value = sess.run(
    [z1, z2],
    feed_dict = {
        x1:1, y1:2,
        x2:[[2],[3]], y2:[[3,3]]
    })
    print(z1_value)
    print(z2_value)

11.0
3.0
[[6. 6.]
 [9. 9.]]


In [0]:
data = pd.read_csv('/titanic_train.csv')

In [52]:
data.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [54]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [0]:
model = Sequential()

model.add(Dense(16, activation='relu', input_shape=(2,)))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [0]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [67]:
data.drop(['SibSp', 'Parch', 'Ticket', 'Embarked', 'Name','Cabin', 'PassengerId', 'Fare', 'Age'], inplace=True, axis=1)

KeyError: ignored

In [0]:
data.dropna(inplace=True)

In [0]:
y = np.ravel(data.Survived) # Make 1D
x = data.drop(['Survived'], axis=1)

In [68]:
model.fit(x, y, epochs=50, batch_size=1, verbose=1)

Epoch 1/50


ValueError: ignored